#!/usr/bin/env bash
# =============================================================================
# e2-deploy.sh — One-shot setup script for GCP e2 VM (Debian/Ubuntu)
# Run as root or with sudo: sudo bash e2-deploy.sh
# =============================================================================
set -euo pipefail

REPO_URL="git@github.com:Vivek2004-web/cost-management.git"
APP_DIR="/opt/cloud-cost-monitor"
COMPOSE_FILE="$APP_DIR/docker-compose.yml"

echo "========================================"
echo "  Cloud Cost Monitor — e2 VM Setup"
echo "========================================"

# 1. Update system packages
echo "[1/6] Updating system packages..."
apt-get update -y && apt-get upgrade -y

# 2. Install Docker Engine
echo "[2/6] Installing Docker Engine..."
if ! command -v docker &>/dev/null; then
  curl -fsSL https://get.docker.com | sh
  systemctl enable docker
  systemctl start docker
  # Allow current user (non-root) to run docker
  usermod -aG docker "${SUDO_USER:-$USER}" || true
else
  echo "  Docker already installed — skipping."
fi

# 3. Install Docker Compose plugin (v2)
echo "[3/6] Installing Docker Compose v2 plugin..."
if ! docker compose version &>/dev/null; then
  apt-get install -y docker-compose-plugin
else
  echo "  Docker Compose already installed — skipping."
fi

# 4. Clone or update the repository
echo "[4/6] Cloning / updating repository..."
if [ -d "$APP_DIR/.git" ]; then
  echo "  Repo exists — pulling latest changes..."
  git -C "$APP_DIR" pull origin main
else
  git clone "$REPO_URL" "$APP_DIR"
fi

cd "$APP_DIR"

# 5. Configure environment — set a strong JWT_SECRET if not already set
echo "[5/6] Configuring environment..."
ENV_FILE="$APP_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  JWT_SECRET=$(openssl rand -hex 32)
  cat > "$ENV_FILE" <<EOF
# Auto-generated by e2-deploy.sh
JWT_SECRET=$JWT_SECRET
EOF
  echo "  Generated new JWT_SECRET and saved to $ENV_FILE"
else
  echo "  .env already exists — skipping auto-generation."
fi

# Export variables for docker compose
set -a
source "$ENV_FILE"
set +a

# 6. Build and start containers
echo "[6/6] Building and starting containers..."
docker compose -f "$COMPOSE_FILE" pull --ignore-buildable 2>/dev/null || true
docker compose -f "$COMPOSE_FILE" up --build -d

echo ""
echo "✅ Deployment complete!"
echo "-------------------------------------------"
echo "  App URL: http://$(curl -s ifconfig.me)"
echo "  Logs:    docker compose -C $APP_DIR logs -f"
echo "  Stop:    docker compose -C $APP_DIR down"
echo "-------------------------------------------"
